name: 2307_roads
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy=1.26.*
  - pandas
  - scipy
  - pytest
  - matplotlib
  - openpyxl
  - rasterio=1.3.*
  - geopandas=0.14.*
  - xarray=2023.7.*
  - rioxarray=0.14.*
  - dask=2023.7.*
  - netCDF4
  - flox
  - xlsxwriter
  - tqdm
  - pip
  - pip:
    - graphviz
    - sparse